services:
  app:
    build: .
    container_name: moviefinder_app
    ports:
      - "8601:8601"
    command: >
      sh -c "python src/pipelines/training_pipeline.py && streamlit run server.py --server.port=8601 --server.address=0.0.0.0"